language: java
services:
  - docker
install: true

env:
  global:
    - IMAGE_NAME=cuzz22000/web-crawler-cli

jdk:
  - openjdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
  
script: 
  - ./gradlew
  
deploy:
  provider: script 
  script: bash scripts/docker-hub.sh
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    